source 'https://github.com/CocoaPods/Specs.git'
plugin 'slather'

target 'NTextView', :exclusive => true do
  pod "NTextView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NTextView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
