# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods activesupport slather --no-ri --no-rdoc
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- slather setup Example/NAsync.xcodeproj
- set -o pipefail && xcodebuild test -workspace Example/NTextView.xcworkspace -scheme NTextView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
after_success: slather
